apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "credit-default-api.fullname" . }}
  labels:
    {{- include "credit-default-api.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ tpl (toString $v) $ | quote }}
  {{- end }}
